### ISSUE TITLE
No confirmation for sign up shown

### ISSUE THREAD

**Issue by arundhatigupta** [NJACKWinterOfCode/online_leave_management_iitp#1]
**Actual Behaviour**

Currently, once the user submits a sign up form, no confirmation is shown.

**Expected Behaviour**

Display an appropriate message after the user signs up successfully. The page that displays the thank you message should contain a link to the login page.

**Comment by shoumikdey** [comment]
Is it necessary to create a new page to show the message or can I just display the message on the login page itself just after an user signs up successfully and is redirected to the login page ?

I have edited the login page to show a message after a successful sign up.

**Comment by arundhatigupta** [comment]
@shoumikdey Seems to be a good idea. But, as there was a need to fix a few things urgently, I fixed this. Now, the project is available with an improved logic. I request you to please go through other open issues and maybe look for more issues that you feel are worth working on. Closing this for now. Sorry for the inconvenience. Looking forward to your contributions to the project. 😃
