### ISSUE TITLE
Add screenshots of the project to README.md

### ISSUE THREAD

**Issue by arundhatigupta** [NJACKWinterOfCode/online_leave_management_iitp#11]
**Actual Behaviour**

Currently, there are no screenshots of the project in README.md.

**Expected Behaviour**

Add upto 6 screenshots in README.md.

**Comment by agarwalrounak** [comment]
I am working on this issue

**Comment by arundhatigupta** [comment]
Sure @agarwalrounak , go ahead! 👍
