### ISSUE TITLE
Dropdowns in Student Sign Up page get distorted

### ISSUE THREAD

**Issue by agarwalrounak** [NJACKWinterOfCode/online_leave_management_iitp#18]
**Actual Behaviour**

On opening the [Sign Up](https://olmiitp.herokuapp.com/signup/) page, the student sign up shows up by default. If we switch from the student to authority sign up and then back to student sign up by making use of the first dropdown, the other dropdowns in the student signup get distorted.

**Expected Behaviour**

All fields should remain centre-aligned even after switching back and forth from student to authority signup.

**Steps to reproduce it**

Go to https://olmiitp.herokuapp.com/signup/ and click on the first dropdown having the options Student and Authority to switch to the authority sign up page. Once, you are on the authority sign up page, again use the first dropdown to switch back to the student sign up page.

**Screenshots of the issue**
- Original Student Sign Up page
![screenshot from 2018-12-07 11-31-50](https://user-images.githubusercontent.com/38394281/49630838-d46d7300-fa15-11e8-9cf8-3adb0753a037.png)
- Student Sign Up page after switching back and forth from student to authority to student sign up page.
![screenshot from 2018-12-07 11-35-22](https://user-images.githubusercontent.com/38394281/49630844-d6cfcd00-fa15-11e8-8f82-c3acad075468.png)

**Would you like to work on the issue?**

Yes

**Comment by 27vinayvyas** [comment]
Hello @agarwalrounak 
I m getting problem in installing django.
Basically i have both python 2.7 and 3,.5 in my ubuntu system. For the latest version of django py 2.7 cannot be used. So i have  to create a venv for my py 3.5. But the pip version is 8.1 and i m having trouble updating it in my venv. Outside the venv, the pip version is updated and is 18.+.

So my problem is the in the venv of py3.5, pip version is showing 8.1(not compatible for latest django version) and outside the venv, py 2.7 is there (not compatible either for latest django version)

Thnx if u could help
