### ISSUE TITLE
Improve UI of leave application form

### ISSUE THREAD

**Issue by arundhatigupta** [NJACKWinterOfCode/online_leave_management_iitp#4]
### Screenshots

**Current UI**

<img width="1440" alt="screenshot 2018-12-01 at 6 02 02 pm" src="https://user-images.githubusercontent.com/30979369/49328249-3865e680-f593-11e8-84d2-d100c0b2f18d.png">

**Expected**

An improved UI. The color scheme and font style must be kept same as used in the entire project.

**Comment by Mirnal1409** [comment]
I am working on this

**Comment by arundhatigupta** [comment]
Okay go ahead! 👍

**Comment by arundhatigupta** [comment]
Hey @Mirnal1409 , as I had been working on this project and there was a need to fix certain things urgently, I have updated the UI for leave application form. Now, the project has been updated and is a bit easier to run as the logic has been corrected. It would be great if you could please have a look at the other open issues or maybe find new issues that you feel need to be fixed. Need to close this issue for now. Looking forward to your contributions on the project. 😃
