### ISSUE TITLE
Bug in Leave create form

### ISSUE THREAD

**Issue by tmsreekanth98** [NJACKWinterOfCode/online_leave_management_iitp#7]
**Actual Behaviour**

After filling Leave Apply form and submitting for first time, django error occurs when form is submitted

**Expected Behaviour**

The form should have submitted successfully.

**Steps to reproduce it**
(This is for new users to the system)
1.Login
2.Apply leave from profile
3.Fill the form
4.Click submit

(The bug occurs only for first time users when they have not entered models.)

**Screenshots of the issue**

![iitp](https://user-images.githubusercontent.com/34984066/49456480-15307680-f7e1-11e8-8cbe-c8b7b7c64981.png)

**Would you like to work on the issue?**

Yes i will fix this issue. I am currently working on it.

**Comment by arundhatigupta** [comment]
Hey @tmsreekanth98 , thanks for finding out this bug. Actually, I had been working on this project for some time. And, had to fix a few things urgently, so this has been fixed. Now, the project logic works correctly. I request you to please have a look at the project now and check out the open issues or maybe open new issues that exist. Need to close this issue as it has been fixed. 🙂

**Comment by tmsreekanth98** [comment]
Glad to help out. I will check the other issues if any.
